### ISSUE TITLE
Treatment of email fields in buildTableRow may be bugged

### ISSUE THREAD

**Issue by ChemiKyle** [ctsit/redcap_entity#11]
Currently, when making entries in a table row, if Entity detects that a cells contains data classified as an `email`, it attempts to format it as `mailto:` link.

https://github.com/ctsit/redcap_entity/blob/b070de0e283ddee5b4ffb155fb3cd6c79ae2f9f1/classes/EntityList.php#L545-L548

The address is set by `$user_info['user_email']`, which (at least in the case of [Project Ownership](https://github.com/ctsit/project_ownership/pull/41)) is null if `$user_info` is not populated (it seems this is only created if the field is type `user`), causing emails to be shown properly, but clicking them does not autofill a recipient. In the linked PR, the solution was to set the field type as `text` and manually build the url (it was also combined into another field).

It may be the case that Project Ownership implemented this feature wrong, but perhaps this is the fix:
```php
case 'email':
    if ($row[$key]) {
        $row[$key] = RCView::a(['href' => 'mailto:' . $row[$key]], $row[$key]);
    }
```

**Comment by pbchase** [comment]
Addressed by PR #18
