### ISSUE TITLE
Statis analysis of version 2.3.1 found some minor issues you might want to consider.

### ISSUE THREAD

**Issue by aarenson** [ctsit/redcap_entity#14]
classes/Entity/DB.php, checkEntityDBTable: $reset_entity_types is unused

classes/Entity/DB.php, buildEntityDBTable: $reset_table is unused

classes/EntityForm.php, validate: $entity_type_info is unused

classes/EntityList.php, $data and $entity are unused

classes/Page.php, $context is unusued

examples/protocols_advanced_v0.0.0/ExternalModule.php, $version is unusued

classes/EntityDB.php
Line 108: $reset used but never set.
Line 135: $q set but never used

classes/EntityForm.php
Line 157: $choices set but never used.

classes/SchemaManagerPage.php
Line 144: $rows_attributes set but never used.

Classes/SchemaManagerPage.php missing namespace

**Comment by ChemiKyle** [comment]
Thanks for conducting this analysis and sorry for taking a while to get back to you on the issue, I had to spend some time setting up an IDE and integrating with PHPMD.

After looking at these, it's apparent that these are mostly crumbs of features a previous developer intended to implement (in two cases it's simply a wrong name for a previous variable). Perhaps not best practice, but I'm going to leave them as-is to avoid reinventing the wheel when their need is realized.
