### ISSUE TITLE
Crash when attempting to enter institution IDs

### ISSUE THREAD

**Issue by aarenson** [ctsit/redcap_entity#19]
https://community.projectredcap.org/questions/78289/invalid-entity-type-when-using-redcap-entity-api-e.html

When attempting to configure the OnCore Client external module (2.3.2) for the first time, and using the REDCap Entity API external module (2.3.1) to store institutional IDs, I get a PHP error that crashes REDCap when I attempt to follow the 'Enter User Insitution IDs'.

PHP: 7.2; REDCap: 9.1.24

Here's the error:

```
REDCap crashed due to an unexpected PHP fatal error!
Error message: Uncaught Exception: Invalid entity type. in /var/www/vhosts/redcap.uits.iu.edu/modules/redcap_entity_v2.3.1/classes/EntityList.php:44 Stack trace: #0 /var/www/vhosts/redcap.uits.iu.edu/modules/redcap_oncore_client_v2.3.2/plugins/oncore_staff_identifier_entry.php(5): REDCapEntity\EntityList->__construct('oncore_staff_id...', Object(OnCoreClient\ExternalModule\ExternalModule)) #1 /var/www/vhosts/redcap.uits.iu.edu/redcap_v9.1.24/ExternalModules/index.php(98): require_once('/var/www/vhosts...') #2 {main} thrown
File: /var/www/vhosts/redcap.uits.iu.edu/modules/redcap_entity_v2.3.1/classes/EntityList.php
Line: 44
```

Here are the values I used for configuring the OnCore Client external module:

- WSDL: https://iuctsi-oncore-ntg.forteresearconcoreapihapps.com/opas/OpasService?wsdl
- Login: OnCoreAPI
- Password: xxxxx
- Protocol lookup method: SIP
- SIP URL: https://iuctsi-oncore-ntg.forteresearchapps.com/sip/SIPMain#
- Log requests: unchecked
- Store Institution IDs in REDCap or Entity database: Entity Database
- Auto-populate Institution ID from server? unchecked

**Comment by ChemiKyle** [comment]
Hi @aarenson,

EDIT: I didn't do my due diligence by checking your REDCap Community post before responding. This is a repeat of @pbchase's response.

I think I may know the root of this issue. If it is what I suspect, it actually stems from the `REDCap OnCore Client`. If you upgraded from a previous version of the `REDCap OnCore Client` module, the table for the institution ID is not created on upgrade.

To remedy:

1. Log in to your REDCap instance as an administrator
1. Navigate to the **Control Center**
1. Click the **Entity DB Manager** in the sidebar
1. You should see a row for `oncore_staff_identifier` with a green button for `create db table` on the far right of the row. Clicking that button will fix your issue
1. Go back to the **Enter User Institution IDs** link in the sidebar to test

Please let me know if this fixes your problem.

**Comment by aarenson** [comment]
In the Entity DB Manager, I see five entities for oncore, including oncore_staff_identifier. All of them have a green 'create db table' button. Clicking the button doesn't do anything. No error messages are displayed on screen or in our httpd error log, even after turning off REDCap's disabling of error reporting in the System.php file.

The status for all five entities is 'Pending'.

Does the Entity DB Manager rely on the cron job to be running? I'm testing this on an instance of REDCap that intentionally has the cron job turned off.

**Comment by aarenson** [comment]
The culprit is, as Philip suggested on the community site, that the database user used by our REDCap instance does not have privileges for creating tables. We've been doing REDCap upgrades with a different database user.

**Comment by pbchase** [comment]
Andy, I'm relieved to hear this. I did one test denying my redcap database user `create` privileges, got quiet failure, but never got `pending`. I looked at the code and could not see another possible cause for failure. I should have shared, but didn't know what to suggest next.
