### ISSUE TITLE
Entity entries with type "JSON" are not shown in EntityForm pages

### ISSUE THREAD

**Issue by ChemiKyle** [ctsit/redcap_entity#23]
In the entity form context, all that is seen for JSON type fields is a blank text box, even if there is an entry in the database.  
I believe this is because they are returned from the server as `stdClass` objects rather than the raw JSON string.

See below an image of the database and the interface:  

![image](https://user-images.githubusercontent.com/20332546/79355292-73a85180-7f0b-11ea-8a55-8c4dc3360eff.png)

The fix is to `json_encode` the data before it gets to the exposure point, I am looking for a place to do that.

By the time the field is being built for the frontend, the data is already bad.  
https://github.com/ctsit/redcap_entity/blob/d7d3158d91daedf365dd911cea494e3f1c627df8/classes/EntityForm.php#L235

___
The breakage occurs here:  
https://github.com/ctsit/redcap_entity/blob/d7d3158d91daedf365dd911cea494e3f1c627df8/classes/EntityForm.php#L138

___

JSON data is set as `stdClass` here:  
https://github.com/ctsit/redcap_entity/blob/d7d3158d91daedf365dd911cea494e3f1c627df8/classes/Entity.php#L248

Easily fixable here by changing to  an array as follows:
```php
                $value = json_decode($value, true);
```
But `stdClass` acts differently and an `(array)` was likely expected. This should be looked at later, for now fixing `EntityForm` corrects this issue but I suspect other problems may arise in other contexts.

**Comment by pbchase** [comment]
closed by PR #24
